version: '3.8'

services:
  app:
    build: .
    depends_on:
      - mysql_db
    links: 
      - mysql_db
    ports:
      - "3000:3000"

  mysql_db:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD:$MYSQLDB_PASSWORD
      - MYSQL_DATABASE:$MYSQLDB_DATA_DB
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
