-- MySQL Script generated by MySQL Workbench
-- Sun May 12 22:30:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema yogu_datadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema yogu_datadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yogu_datadb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `yogu_datadb` ;

-- -----------------------------------------------------
-- Table `yogu_datadb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yogu_datadb`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(150) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `email` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `yogu_datadb`.`cereal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yogu_datadb`.`cereal` (
  `id_cereal` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `price` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_cereal`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `yogu_datadb`.`fruits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yogu_datadb`.`fruits` (
  `id_fruits` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `price` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_fruits`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `yogu_datadb`.`ice_cream`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yogu_datadb`.`ice_cream` (
  `id_ice_cream` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `price` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_ice_cream`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `yogu_datadb`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yogu_datadb`.`type` (
  `id_type` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `price` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_type`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `yogu_datadb`.`yogur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yogu_datadb`.`yogur` (
  `id_yogur` INT NOT NULL AUTO_INCREMENT,
  `id_type` INT NULL DEFAULT NULL,
  `id_fruits` INT NULL DEFAULT NULL,
  `id_ice_cream` INT NULL DEFAULT NULL,
  `id_cereal` INT NULL DEFAULT NULL,
  `size` INT NULL DEFAULT NULL,
  `price` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_yogur`),
  INDEX `fk_type_idx` (`id_type` ASC) VISIBLE,
  INDEX `fk_fruit_idx` (`id_fruits` ASC) VISIBLE,
  INDEX `fk_ice_cream_idx` (`id_ice_cream` ASC) VISIBLE,
  INDEX `fk_cereal_idx` (`id_cereal` ASC) VISIBLE,
  CONSTRAINT `fk_cereal_yogu`
    FOREIGN KEY (`id_cereal`)
    REFERENCES `yogu_datadb`.`cereal` (`id_cereal`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_fruits_yogu`
    FOREIGN KEY (`id_fruits`)
    REFERENCES `yogu_datadb`.`fruits` (`id_fruits`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ice_cream_yogu`
    FOREIGN KEY (`id_ice_cream`)
    REFERENCES `yogu_datadb`.`ice_cream` (`id_ice_cream`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_type_yogu`
    FOREIGN KEY (`id_type`)
    REFERENCES `yogu_datadb`.`type` (`id_type`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `yogu_datadb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yogu_datadb`.`order` (
  `id_order` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NULL DEFAULT NULL,
  `id_yogu` INT NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `payment` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_order`),
  INDEX `fk_user_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_yogu_idx` (`id_yogu` ASC) VISIBLE,
  CONSTRAINT `fk_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `yogu_datadb`.`user` (`id_user`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_yogu`
    FOREIGN KEY (`id_yogu`)
    REFERENCES `yogu_datadb`.`yogur` (`id_yogur`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `yogu_datadb`.`billing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yogu_datadb`.`billing` (
  `id_billing` INT NOT NULL AUTO_INCREMENT,
  `id_order` INT NULL DEFAULT NULL,
  `price` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_billing`),
  INDEX `fk_order_idx` (`id_order` ASC) VISIBLE,
  CONSTRAINT `fk_order`
    FOREIGN KEY (`id_order`)
    REFERENCES `yogu_datadb`.`order` (`id_order`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `yogu_datadb`.`milk`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yogu_datadb`.`milk` (
  `id_milk` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `price` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_milk`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `yogu_datadb`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yogu_datadb`.`stock` (
  `id_stock` INT NOT NULL AUTO_INCREMENT,
  `id_fruits` INT NULL DEFAULT NULL,
  `id_cereal` INT NULL DEFAULT NULL,
  `id_milk` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_stock`),
  INDEX `fk_fruit_idx` (`id_fruits` ASC) VISIBLE,
  INDEX `fk_cereal_idx` (`id_cereal` ASC) VISIBLE,
  INDEX `fk_milk_idx` (`id_milk` ASC) VISIBLE,
  CONSTRAINT `fk_cereal`
    FOREIGN KEY (`id_cereal`)
    REFERENCES `yogu_datadb`.`cereal` (`id_cereal`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_fruit`
    FOREIGN KEY (`id_fruits`)
    REFERENCES `yogu_datadb`.`fruits` (`id_fruits`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_milk`
    FOREIGN KEY (`id_milk`)
    REFERENCES `yogu_datadb`.`milk` (`id_milk`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
